name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          plugin_lines_delay: 120
          repositories_affiliations: owner, organization_member
          token: ${{ secrets.METRICS_TOKEN }}
          base_hireable: yes
          base_indepth: yes
          plugin_lines: yes
      - name: Activities
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_affiliations: ""
